### ISSUE TITLE
Comparison Operators

### ISSUE THREAD

**Issue by ashleyHutton** [wuest/simd-ruby#1]
We're using this library to optimize a lot of our array math in one of our projects. It is amazing! We'd like the ability to use comparison operators (<, >, etc.), but we are unfamiliar with C. Is this functionality something that could be added to this package?

**Comment by wuest** [comment]
I see that this was addressed in a fork by @nathancolgate - but the PR was closed due to being lost while I was mostly dealing with having recently moved.

:wave: @nathancolgate - would you mind if I merged your changes and cut a new version?

**Comment by nathancolgate** [comment]
👋 @wuest - please do!

**Comment by wuest** [comment]
Circling back: comparison operators are now available for all types in `0.5.2`, which has been pushed to RubyGems.

Thanks for the feedback, and thank you Nathan for the assist!

**Comment by ashleyHutton** [comment]
This is great @wuest, thank you! I hope the move went smoothly. :)
